### ISSUE TITLE
For those who can't run this in Laravel

### ISSUE THREAD

**Issue by kashx** [laracasts/PHP-Vars-To-Js-Transformer#100]
You can use Blade in your view file as JS also. Apparently, all of the Blade code gets compiled, doesn't matter where it is.
For example, I've set my controller to return a total number of posts to my view:
![screen shot 2017-06-24 at 7 17 08 pm](https://user-images.githubusercontent.com/20632252/27510100-c7d15ddc-5912-11e7-91f5-0c13d6837882.png)
Then in my view file I used blade in my <script> tag to echo out the values that I got from my controller:
![screen shot 2017-06-24 at 7 17 32 pm](https://user-images.githubusercontent.com/20632252/27510111-fdd0fc44-5912-11e7-9213-0ee7385e6aea.png)
As you can see you can even use if conditions, as if you were using it normally. Ofcourse you need to write it inline because it's JavaScript. And as a result you get this (inspector):
![screen shot 2017-06-24 at 7 17 53 pm](https://user-images.githubusercontent.com/20632252/27510120-2fa0538c-5913-11e7-9d7c-4935a30840e3.png)
I used this to pass some values to my Vue component so that I could use v-if functionality.

Keep in mind that people can change these JS values by turning on network throttling in the inspector and changing it before it actually gets loaded. In my case I've tried to spam "totalPosts = 1" and it worked. So somebody could even change the value of isAdmin if they wanted to. So you should take that into consideration not to use it for something important.

I am only a beginner dev (it's my 3rd month learning stuff) so I don't know if this is working exactly like this package. But I tried changing the value before the page load with this package and it worked also.

P.S. sorry for my english - it's not my first language. Hope this post helps someone!

**Comment by autaut03** [comment]
Hey! Thanks for the information.

But why would you use if(something) then true else false? This doesn't make any sense. Isn't it better to write something like this:

let isLogged = {{ Auth::check() }}

**Comment by kashx** [comment]
Oh, right. I know that this way it works exactly the same. As I’ve said I’m only starting this. Not only with Laravel but with programming itself. Sorry!

**Comment by ankurk91** [comment]
Have you tried -
https://github.com/spatie/laravel-blade-javascript
