### ISSUE TITLE
Laravel 5.0 Support

### ISSUE THREAD

**Issue by adamgoose** [laracasts/PHP-Vars-To-Js-Transformer#26]
Jeff -

Will you be adding L5.0 support? I could use it right about now!

Thanks,
Adam.

**Comment by sdebacker** [comment]
+1

**Comment by mbardelmeijer** [comment]
+1

**Comment by christianrojas** [comment]
+1

**Comment by sdebacker** [comment]
I’ve no problem with this package and Laravel 5.

**Comment by seblavoie** [comment]
@sdebacker Could you please explain a little how you set it up? What did you do different from what is explained in the docs?

**Comment by sdebacker** [comment]
Did you use version 2.0 ? I just added "laracasts/utilities": "~2.0" in my composer file. What problem do you have ?

**Comment by seblavoie** [comment]
Yes, I did use version 2.0 and added `'Laracasts\Utilities\JavaScript\JavascriptServiceProvider'` to my `config/app.php` as stated in the readme, but I get a `Class 'Project\Http\Controllers\JavaScript' not found` error. I suppose I have to somehow load that class but loading the facade did not fix the issue. So, that is where I'm stuck.

**Comment by sdebacker** [comment]
See, it'a a case problem. Try with Javascript in place ou JavaScript.

**Comment by VMosoti** [comment]
I have followed all the instructions but its not working either. @seblavoie did you fix it?

**Comment by seblavoie** [comment]
Yes, I just did. There were two problems, with my setup. The first one was the namespace problem as identified by @sdebacker (thank you by the way!). The second was that I did not understand at first that publishing config files and pointing `bind_js_vars_to_this_view` to a file (using the dot notation, which is not *yet* specified), was mandatory. I'll try making a pull request to make it clearer when I'll have a couple of minutes.

**Comment by cnweibo** [comment]
@sdebacker , thanks for your tip, with namespace "use Javascript", i now can use jeff's php to js utilities. Unfortunately, i can not understand, when I just use \Javascript::put(), it also says class not found! I assume the Javascript class lives in the root namespace, why that not work? For the View facade instead, when I just use \View::make(), it works. Can you give a small explaination, why that happen?
Thanks!

**Comment by sdebacker** [comment]
@cnweibo and with \JavaScript::put() (with a uppercase 'S') ?

**Comment by cnweibo** [comment]
@sdebacker :+1: Thanks for your hint. When I change to \JavaScript::put()  without use Javascript, it works also. Does that mean JavaScript(Uppercase S) is the class exported by PHP-Vars-To-Js-Transformer? Javascript(lower case s)is the namespace of JavaScript? 
Thanks!

**Comment by adamgoose** [comment]
Fixed with the 2.0 branch (fb96d2de843086af87b175c890d75561da66d393)
