### ISSUE TITLE
Laravel 5: Only dot notation supported for bind_js_vars_to_this_view

### ISSUE THREAD

**Issue by rspahni** [laracasts/PHP-Vars-To-Js-Transformer#27]
Rather a warning for other users than an issue: After one of Taylor's recent commits (probably this PR here: https://github.com/laravel/framework/commit/e01a6c258a03bef6aaa73deb3c04d7061ab8217b), the transformer now requires ```bind_js_vars_to_this_view``` setting in the config file to be dot notated. Slashs are no longer supported. If one puts e.g. 'partials/jsbody', nothing at all will happen anymore - not even an error message. Anywhere else in L5 the slash continues to work.

**Comment by willvincent** [comment]
PR #45 addresses this.
