### ISSUE TITLE
Add CDATA to print valid xml

### ISSUE THREAD

**Issue by timersys** [laracasts/PHP-Vars-To-Js-Transformer#32]
It would be great if you add <![CDATA[ to print valid xml the same way as wp_localize_script from wordpress does 

So for example it will print something like 

    <script type="text/javascript">/* <![CDATA[ */
    var myVarName = {"ajax_url":"http:\/\/www.tutsplus.com\/wp-admin\/admin- ajax.php","nonce":"dsfsdf123r"};
    /* ]]> */</script>

**Comment by willvincent** [comment]
Created a pull request for this: #43

**Comment by williamoliveira** [comment]
+1
