### ISSUE TITLE
Class 'App\Http\Controllers\JavaScript' not found

### ISSUE THREAD

**Issue by dotMastaz** [laracasts/PHP-Vars-To-Js-Transformer#37]

**Comment by GrahamCampbell** [comment]
Looks like you forgot to import the class...

**Comment by GrahamCampbell** [comment]
`use Laracasts\Utilities\JavaScript\JavaScriptFacade as JavaScript`.

**Comment by dotMastaz** [comment]
Ok, and where i add it ?

Thank you Graham!

**Comment by GrahamCampbell** [comment]
http://php.net/manual/en/language.namespaces.importing.php

**Comment by dotMastaz** [comment]
Well done, but : Uncaught ReferenceError: foo is not defined ?
