### ISSUE TITLE
Uncaught ReferenceError: age is not defined

### ISSUE THREAD

**Issue by dotMastaz** [laracasts/PHP-Vars-To-Js-Transformer#39]
Hello,

Value is not populate ?
Uncaught ReferenceError: age is not defined ?

Any idea ?!
Thank you !

**Comment by GrahamCampbell** [comment]
We're going to need a lot more info that that!

**Comment by dotMastaz** [comment]
Sorry,

I test your script with your example.
- Composer require : ok
- Providers : ok
- Call JavaScript facade : ok

I put this in route.php :
JavaScript::put(['age' => 29]);

and try to call 'age' in hello.blade.php :
console.log(age);

But i have this error :+1: 
Uncaught ReferenceError: age is not defined ?

Thank you !

**Comment by dotMastaz** [comment]
Any idea or help :) ?!
