### ISSUE TITLE
Class 'Laracasts\Utilities\JavaScript\JavaScriptServiceProvider' not found

### ISSUE THREAD

**Issue by DougSisk** [laracasts/PHP-Vars-To-Js-Transformer#40]
I'm using a Forge provisioned server and I'm getting this error no matter what I do:

    PHP Fatal error:  Class 'Laracasts\Utilities\JavaScript\JavaScriptServiceProvider' not found in /home/forge/siteurl/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 15

Checked the `vendor` folder, and all the files are there. Don't know what's going on. Works fine in my Homestead.

**Comment by DougSisk** [comment]
PR #36 seems to fix the issue

**Comment by laracasts** [comment]
use `Laracasts\Utilities\JavaScript\JavascriptServiceProvider`.
