### ISSUE TITLE
JavaScript Not recognized

### ISSUE THREAD

**Issue by reinvanleirsberghe** [laracasts/PHP-Vars-To-Js-Transformer#47]
I installed the package successfully, added 'Laracasts\Utilities\JavaScript\JavascriptServiceProvider' to the providers-array in de app.php file, but for some reason I can not use JavaScript.

I always get the error Class 'App\Http\Controllers\JavaScript' not found.
I am using Laravel 5 and PHPstorm. PHPstorm can also not find the JavaScript...

Thanks!

**Comment by kiaking** [comment]
Within controller, you might need to "use" it like below?

```
use JavaScript;

class HomeController extends Controller
{
    public function index()
    {
        JavaScript::put(['locale' => config('app.locale')]);
        
        return view('home.index');
    }
}
```

**Comment by nolros** [comment]
@reinvanleirsberghe did you find a solution? I'm running into the same problem. I've have the ServiceProvider installed, run config install. I've tried adding teh alias to the Facade myself, but it fails. If I run dd() in the JS ServiceProvider boot I can see that is calling it, but fr some reason the alias is not working

**Comment by rpcvronw** [comment]
I needed to add a backslash:
```
public function index()
{
    \JavaScript::put([
        'foo' => 'bar',
        'user' => User::first(),
        'age' => 29
    ]);

    return View::make('hello');
}
```
