### ISSUE TITLE
Not working with redirects.

### ISSUE THREAD

**Issue by neeravp** [laracasts/PHP-Vars-To-Js-Transformer#48]
I am trying to put the authenticated user's role to access it from angular front end.
So in my AuthController
    
    if ($this->auth->attempt(['email'=>$email, 'password' =>$password, 'status'=>'active'],$request->has('remember')))
    {
        $user = $this->auth->user();
        JavaScript::put(['user' =>$user]);
        return redirect()->intended($this->redirectPath()); //doesn't work
        //But if I return view instead of a redirect as below it works
        return view('home'); //it works
    }
  
What should I do to make it work with a redirect?

**Comment by PrettyHotProgrammer** [comment]
Redirects are not supported. You must pass your JavaScript data after the redirect has already taken place.

**Comment by neeravp** [comment]
I am sorry for responding this late.
But I still can't figure out how to pass data after redirect. Any statement after `return redirect()` will be inaccessible.  
For ex: In the following snippet from controller code, the JavaScript data assignment would be inaccessible.
    
    if ($this->auth->attempt(['email'=>$email, 'password' =>$password,    'status'=>'active'],$request->has('remember')))
    {
        $user = $this->auth->user();       
        return redirect()->intended($this->redirectPath()); 
         JavaScript::put(['user' =>$user]);  // this would be inaccessable
    }

**Comment by jeffwalsh** [comment]
neeravp, it's because you are "returning" after the redirect. No code below a "return" will be processed - you have left that part of the ode and on to the intended redirect.

**Comment by neeravp** [comment]
Thanks jeffwalsh.
I didn't occur to me to put it in the intended's controller. I will give it a try.
Thanks again.
