### ISSUE TITLE
variable in Javascript is undefined

### ISSUE THREAD

**Issue by thienvulai** [laracasts/PHP-Vars-To-Js-Transformer#49]
Hi everyone,
im using laravel 5 and angularjs for my project. And i needed to pass value from laravel to angularjs. So i installed PHP-Vars-To-Js-Transformer. it was successful. But i cannot access to Javascript variable in View:

LanguageController.php:

     public function create()
	{
		$names = $this->initLang();

		JavaScript::put([
	        'foo' => 'bar',
	        'langs' => $names,
	        'age' => 29
	    ]);
		
		return View::make('NAATIMockTest.Admin.Language.create',compact('names'));
	}
my route:

    // Route create
    Route::get('/Admin/Language/create', 'NAATIMockTest\LanguageController@create');

my View create.blade.php:

         <input type="text" name="search" ng-model="search">
             <select name="Name[]" multiple size="10" >
                     <option value="@{{x}}" ng-repeat="x in langs | filter:search">@{{x}}</option>
            </select><br>

javascript on create.blade.php:

	var app = angular.module('myApp', []);
	app.controller('langCtrl', ['$scope', '$http', function($scope, $http) {
		console.log(window.foo); // bar
		// console.log(user); // User Obj
		console.log(window.age); // 29
		console.log(window.langs);
	}]);

But when i check console: there are three lines undefined. Is there anyone can help.

**Comment by jamesaspence** [comment]
Having the same issue here.

**Comment by jamesaspence** [comment]
I figured it out. You need to edit your config/javascript.php file to tell it which view / partial to prepend your variables to. So, I ended up prepending them to my template blade file, and they're always included.

**Comment by matq007** [comment]
I had to use dot notation 'bind_js_vars_to_this_view' => 'include.footer' to get it to work :)
