### ISSUE TITLE
Check for JsonSerializable

### ISSUE THREAD

**Issue by aranw** [laracasts/PHP-Vars-To-Js-Transformer#55]
The Transformer should check to see whether a object implements the [JsonSerializable](https://secure.php.net/manual/en/class.jsonserializable.php) interface. If so then the object can be safely passed along to the json_encode function later on down the line.

**Comment by ipsq** [comment]
http://php.net/manual/en/function.class-implements.php

http://php.net/manual/en/class.jsonserializable.php

Only change that needs to be made is an addition before the check for a `toJson` method.
