### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by bihlmaierh** [laracasts/PHP-Vars-To-Js-Transformer#58]
Is there support for Laravel 5.1 ?

**Comment by sukonovs** [comment]
Package works on newest Laravel version. At least if you are using dev-master.

**Comment by galata90** [comment]
I installed the package successfully, but for some reason I can not use JavaScript.

I always get the error Class 'App\Http\Controllers\JavaScript' not found.
I am using Laravel 5.1.

Thanks!

**Comment by sukonovs** [comment]
You may try to use \JavaScript::put() instead of JavaScript::put(). Looks like problem with namespaces not package.

**Comment by galata90** [comment]
I tried, but unsuccessfully

**Comment by cendekia** [comment]
You need to run 'php artisan vendor:publish' first

**Comment by aminking2005** [comment]
it dose'nt work for me too in L5.1 . should i add any facad aliase in app.php?

**Comment by aminking2005** [comment]
SOLVED!!
1-first of all add a facade to app.php (for me it is 
'JS' => Laracasts\Utilities\JavaScript\JavaScriptFacade::class  )

2- if you use ide helper run following code

"php artisan clear-compiled",
        "php artisan ide-helper:generate",
        "php artisan optimize"

3- run 'php artisan vendor:publish' . so you can set footer path but becarfull , if your footer is located in partials/footer you should use  'bind_js_vars_to_this_view' => 'partials.footer'
NOT  'bind_js_vars_to_this_view' => 'partials/footer',
so use period insted off slash!
thats finish
