### ISSUE TITLE
DOCTYPE issue on internet explorer

### ISSUE THREAD

**Issue by toorta** [laracasts/PHP-Vars-To-Js-Transformer#59]
Because of the fact that the code is put on top of the html before <!DOCTYPE html>, the browser can't detect the doctype and there becomes css issues on internet explorer 9 or below...

**Comment by Propaganistas** [comment]
You are experiencing this because you're binding the JS vars to your master view. The vars get *prepended* to the specified view, so in your case before the doctype declaration.

Try binding it to a subview like a footer or equivalent.

    /*
    |--------------------------------------------------------------------------
    | View to Bind JavaScript Vars To
    |--------------------------------------------------------------------------
    |
    | Set this value to the name of the view (or partial) that
    | you want to prepend all JavaScript variables to.
    |
    */
    'bind_js_vars_to_this_view' => 'footer',

**Comment by toorta** [comment]
That's it... Thanks...
