### ISSUE TITLE
<!DOCTYPE html>

### ISSUE THREAD

**Issue by VIco21** [laracasts/PHP-Vars-To-Js-Transformer#62]
The javascript is displayed at the beginning of the file, so before the doctype. Is there a way to put the javascript elsewhere?

Because of this, my DOCTYPE is just ignored. 

Thanks

**Comment by sukonovs** [comment]
You can bind it to some partial in footer. Not master template.

**Comment by pbhanu1994** [comment]
Put the Javascript file just above the body tag and you are good to go :+1:
