### ISSUE TITLE
Please use window['key'] instead window.key

### ISSUE THREAD

**Issue by kocoten1992** [laracasts/PHP-Vars-To-Js-Transformer#67]
As it turn out, if I have key name : try-this-key

When using JavaScript::put(['try-this-key' => 'value'])

JavaScript will not understand as window.try-this-key, but it will understand window['try-this-key']

Should we change to that?

**Comment by kocoten1992** [comment]
I make a pull request, hope you accept it

**Comment by willvincent** [comment]
There's nothing to change here.. this is just the way javascript is.. object params can be access with dot or bracket notation, but params with dashes in their names, or with any sort of reserved keyword names cannot be accessed with dot notation.
