### ISSUE TITLE
strange css behaviour

### ISSUE THREAD

**Issue by Artem-Schander** [laracasts/PHP-Vars-To-Js-Transformer#71]
i've noticed visual differences before and after using `JavaScript::put()`

**BEFORE**
![bildschirmfoto 2015-12-06 um 23 42 06](https://cloud.githubusercontent.com/assets/1243826/11616134/6a18509e-9c74-11e5-8d66-488cc1eccc50.png)

**AFTER**
![bildschirmfoto 2015-12-06 um 23 44 29](https://cloud.githubusercontent.com/assets/1243826/11616135/6a1b1860-9c74-11e5-821b-4bad3413eda4.png)

Is there a simple way to fix it?

**Comment by simonpih** [comment]
Have the same problem with font-size, it changes after calling Javascript::put..

**Comment by Artem-Schander** [comment]
The problem is, that `Javascript::put()` echoes php values outside the `<html>` tag.
So you can solve this issue by placing the result of `Javascript::put()` manually into your html, so it doesn't break.

Example:

PHP
```
$js = JavaScript::buildJavaScriptSyntax([
    'foobar' => $someModel->load('foo.bar')
]);
view('main', compact('js'));
```
Blade
```
<script>{!! $js or null !!}</script>
```

**Comment by simonpih** [comment]
Nice and simple, thanks!

**Comment by fullstackfool** [comment]
Better solution:

https://github.com/laracasts/PHP-Vars-To-Js-Transformer/issues/62

**Comment by freshcoderchan** [comment]
Hi, @Artem-Schander 
Sorry, when I use your code, I have some errors.
```
$js = JavaScript::buildJavaScriptSyntax([
    'foobar' => $someModel->load('foo.bar')
]);
view('main', compact('js'));
```

My issue:
![image](https://user-images.githubusercontent.com/35806009/49664740-6ea3da00-fa5b-11e8-9271-3b754bc728dc.png)

Larave version is 5.6

**Comment by freshcoderchan** [comment]
I have fixed using `JavaScript::constructJavaScript`
Thanks.

**Comment by Artem-Schander** [comment]
@freshcoderchan 
I haven't used this for a time, but the docs say:
> This package, by default, binds your JavaScript variables to a "footer" view, which you will include. For example:
> ```php
> <body>
>     <h1>My Page</h1>
> 
>     @include ('footer') // <-- Variables prepended to this view
> </body>
> ```

So it seems you just need to include the `footer` and the issue should be gone
