### ISSUE TITLE
Laravel 5.1.24 (LTS) variable is undefined

### ISSUE THREAD

**Issue by AlexDar** [laracasts/PHP-Vars-To-Js-Transformer#72]
I've gone through the process of setting this up multiple times but the end result is nothing each time. `window.varName undefined`. Other solved issues haven't worked, any help would be greatly appreciated.

Laravel Framework version 5.1.24 (LTS)

    //composer.json

    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "laracasts/utilities": "^2.1"
    }

    //app.php

     'providers' => [
        ...
        App\Providers\RouteServiceProvider::class,
        'Laracasts\Utilities\JavaScript\JavaScriptServiceProvider',
     ]

    'aliases' => [
        ...
        'View'      => Illuminate\Support\Facades\View::class,
        'JS'        => Laracasts\Utilities\JavaScript\JavaScriptFacade::class,
    ]

    //javascript.php

    return [
        'bind_js_vars_to_this_view' => 'home',
        'js_namespace' => 'window'
    ];

    //controller

    <?php

     namespace App\Http\Controllers;

     use App\Theater;
     use App\Http\Controllers\Controller;
     use Illuminate\Http\Request;
     use JavaScript;

     class NavigationController extends Controller
     {
        /* Load the home page without geolocation activated */
        public function indexWithoutGeoLocation(){
           $theaters = Theater::get();

         \JavaScript::put([
           'complexName' => 65
         ]);

      return view('home',[
        'theaters' => $theaters
      ]); 
    }

my view is located at `resources/views/home.blade.php` and is a full view (no yields or includes) from `<html>` to `</html>`

If functionality is relevant, I'm returning a PHP instance of $theaters to render a default page, and a JS version of theaters to update the page afterwords via AJAX.

I have tried adding a facade manually by adding `'JS' => Laracasts\Utilities\JavaScript\JavaScriptFacade::class` as suggested in https://github.com/laracasts/PHP-Vars-To-Js-Transformer/issues/58 but this did nothing.

Additionally I have tried and failed to use `\JavaScript::put()` instead of `JavaScript::put()`

**Comment by swimlappy** [comment]
Once you add the facade, you reference that in your code.  So you would ```use JS;``` at the top of your controller and then ```JS::put()```.  That worked for me.

**Comment by AlexDar** [comment]
Just tried @swimlappy's suggestion. Unfortunately didn't work.

**Comment by swimlappy** [comment]
Hmm, last suggestion would be to change the provider in ```config/app.php``` to ```Laracasts\Utilities\JavaScript\JavaScriptServiceProvider::class```.  That's the only other difference I can see.  I just tried this package for the first time the other day.

**Comment by AlexDar** [comment]
That did it, thanks!

**Comment by Duansoft** [comment]
I have troubles for 3 hours but didn't work.  appreciated for any help.

// composer json
 "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "laracasts/utilities": "~2.1"
    }


//  app.php
provider = [
         ... ,
          Laracasts\Utilities\JavaScript\JavaScriptServiceProvider::class,
]
 'aliases' => [
        'JS' => Laracasts\Utilities\JavaScript\JavaScriptFacade::class,


// javascript.php
return [
    'bind_js_vars_to_this_view' => 'includes.footer',
    'js_namespace' => 'window'
];

What's wrong with my code? 
// controller

namespace App\Http\Controllers;

use JS;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;


namespace App\Http\Controllers;

use JS;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class UserManagerController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {

        JS::put([
            'foo' => 'bar',
            'user' => User::first(),
            'age' => 2
        ]);

        //return View('adminpanel.usermanager');
        return View('adminpanel.usermanager');
    }
