### ISSUE TITLE
Argument 1 passed to Tshafer\Utilities\JavaScript\LaravelViewBinder am getting this in laravel 5.1

### ISSUE THREAD

**Issue by prakashchokalingam** [laracasts/PHP-Vars-To-Js-Transformer#76]
Argument 1 passed to Tshafer\Utilities\JavaScript\LaravelViewBinder::__construct() must be an instance of Illuminate\Contracts\Dispatcher, instance of Illuminate\Events\Dispatcher given, called in /Users/user/Desktop/laravel/vendor/tshafer/utilities/src/JavascriptServiceProvider.php on line 32 and defined

**Comment by JeffreyWay** [comment]
Late reply, but I assume you were using an older version of Laravel.
