### ISSUE TITLE
Its not working for Laravel 5.2 ?

### ISSUE THREAD

**Issue by srikanth240369** [laracasts/PHP-Vars-To-Js-Transformer#77]
Previously I was used this package in laravel 5.1 & I recently Migrated to 5.2 there I am facing problem
this package not working in  5.2 & I dont know suport is there for 5.2 or not

**Comment by SuperlativeEntity** [comment]
I'm using 5.2 without any issues.

**Comment by KyleMay** [comment]
Not working for me on a fresh 5.2 install

**Comment by srikanth240369** [comment]
For me it is working , please refer ur empty blade in config file

    'bind_js_vars_to_this_view' => 'footer'

**Comment by autaut03** [comment]
same. nothing works.

**Comment by autaut03** [comment]
I think author wont update this anymore. If anybody can - fork this and fix the problem.. I would do it, if I knew what's the problem.

**Comment by jbcanas** [comment]
Worked on my 5.2 all I did was

1. php artisan vendor:publish
2. edit config/javascript.php
3. put the name of the view you want this to prepend, mine was **partials.footer**
    

> 'bind_js_vars_to_this_view' => 'partials.footer',

**Comment by autaut03** [comment]
@jbcanas I did all this. As name of the view I put 'app' - which is my main template. NOTHING works.

**Comment by jbcanas** [comment]
@autaut03 do you have some kind of js console errors?

**Comment by autaut03** [comment]
@jbcanas UPD: everything works fine now. I did NOTHING. wtf..

**Comment by jbcanas** [comment]
@autaut03 that's great ;)

**Comment by ctf0** [comment]
@jbcanas am binding to `layouts.app` which is the main layout and getting error in console 
`Uncaught ReferenceError: injected is not defined`
injected = namespace

**Comment by jbcanas** [comment]
@ctf0 this means **injected** variable is not present in your page. Does your code look like this?

`Javascript::put([
	'injected' => $theCodeYouWantToSendToYourJavascript
]);`

**Comment by ctf0** [comment]
yeap

**Comment by jbcanas** [comment]
It's not temporary because it's been declared globally. Can you type the **injected** variable in the console of your browsers dev tools and see if its there or undefined?

**Comment by ctf0** [comment]
sorry for the late answer, just got home
did what u just told me and got new error `Uncaught ReferenceError: injected is not defined(…)`

**Comment by jbcanas** [comment]
@ctf0 it seems not working on your end. You can try to chat with me on gitter https://gitter.im/jbcanas/php-to-vars?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by ctf0** [comment]
okay 👍

**Comment by Younesi** [comment]
It's not working for me too

**Comment by mahfuz05** [comment]
just change 
'bind_js_vars_to_this_view' => 'frontend.layouts.partials.js',
 'js_namespace' => 'injected'

it will work

**Comment by chanux** [comment]
Remember to run `php artisan vendor:publish` accordingly[1]

Also the command is different for Laravel 4.2 (laracasts/utilities 1.0+).

`php artisan config:publish laracasts/utilities`

Check the docs in 1.0/1.0.1 branch for details.

[1] https://laravel.com/docs/5.0/packages#publishing-file-groups
