### ISSUE TITLE
php array being converted into object

### ISSUE THREAD

**Issue by lorvent** [laracasts/PHP-Vars-To-Js-Transformer#78]
if i pass
```
JavaScript::put([
            'foo' => 'bar',
            'age' => 29,
            'load_statuses' => $this->load_statuses, //which is an array
        ]);
```

its giving me object....how can i get array instead of object?

**Comment by shez1983** [comment]
Can you let me know what you did to solve this? I am running into same problem as you @lorvent

**Comment by lorvent** [comment]
@shez1983  since javascript doesn't have good support for object, you can write a custom function or use underscore.js

but i converted my object into array while passing as its easy solution.

**Comment by fullstackfool** [comment]
For anyone finding this issue in the future with collections, `toArray()` didn't work for me, but `values()` did.

```
JavaScript::put([
            'foo' => 'bar',
            'age' => 29,
            'array' => $collection->values(),
        ]);
```
