### ISSUE TITLE
anything other than window cuz undefined error & temp fix.

### ISSUE THREAD

**Issue by ctf0** [laracasts/PHP-Vars-To-Js-Transformer#80]
currently if we used any other namespace than **window** we would get
`Uncaught ReferenceError: namespace_name is not defined`

so to fix that we would use

``` php
// Providers/AppServiceProvider.php
public function boot()
    {
       // ...
       JavaScript::put([
            'the_var_name' => null,
            // any more vars u use
        ]);
    }
```

so now everything works as expected and no more errors.

**Comment by demonmind** [comment]
change the namespace in javascript.php under config folder to whatever you need it to be. Worked for me

**Comment by ctf0** [comment]
have u checked the devtools console ?, without the above way around u should get an error

**Comment by demonmind** [comment]
I got that error and then declaring the namespace in javascript.php fixed the issue. The issue i have now is the variable value is escaped when rendered in the html and does not look like a json string.
