### ISSUE TITLE
Trait not found

### ISSUE THREAD

**Issue by thinkerytim** [laracasts/PHP-Vars-To-Js-Transformer#83]
Followed the install instructions for a Laravel 5.2.39 site. 

1) `composer require laracasts/utilities`
2) added `Laracasts\Utilities\JavaScript\JavaScriptServiceProvider::class()` to `config.app` providers block
3) ran `php artisan vendor:publish` and verified existence of `config/javascript.php`
4) added `use JavaScript` inside class declaration
5) used `JavaScript::put` in `index` method of controller

when page loads it throws error `Trait App\Http\Controllers\JavaScript not found`.

I tried `composer dump-autoload` with no change, and tried using full path to library in `use`, same basic error, just different path.

**Comment by sweijdt** [comment]
It's not used as a trait. Above the class declaration in your controller file add ```use Javascript;```
Just like that
