### ISSUE TITLE
Not working for Laravel 5.3

### ISSUE THREAD

**Issue by mschink** [laracasts/PHP-Vars-To-Js-Transformer#91]
I've followed the documentation very closely and it's still missing something, perhaps namespace related?

Here's my composer.json:
```
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
	"laracasts/utilities": "~2.0"
    },
```
Then in cmd:
> composer update

results in `vendor\laracasts\utilities\` as expected

Then I modify app.php:
```
    'providers' => [
        /*
         * Laravel Framework Service Providers...
         */
        ...
        `Laracasts\Utilities\JavaScript\JavaScriptServiceProvider`
    ],
```

Here's the part where I think there's definitely some issue in 5.3, because `php artisan vendor:publish` gives the following output:
```
Copied Directory [\vendor\laravel\framework\src\Illuminate\Notifications\resources\views] To [\resources\views\vendor\notifications]
Copied Directory [\vendor\laravel\framework\src\Illuminate\Pagination\resources\views] To [\resources\views\vendor\pagination]
Publishing complete for tag []!
```
No mention of the config for javascript, and there's no javascript.php file copied to `config/`

But maybe it will still work, so in my `IndexController.php`
```
namespace App\Http\Controllers;
...
use JavaScript;
...
class IndexController extends Controller
{
  public function getIndex(){
  JavaScript::put([
    'foo' => 'bar'
    ]);
```
Results in the following error:
```
FatalThrowableError in IndexController.php line 38:
Class 'JavaScript' not found
```

**Comment by eugenevdm** [comment]
I tested with two Laravel 5.3 projects, one small site and a completely new install, and it worked.

Some pointers:

1. In config/app.php I needed:

`Laracasts\Utilities\JavaScript\JavaScriptServiceProvider::class,` 

as I have a later PHP version. Make absolutely sure you have this as above.

2. I had to create a blank footer.blade.php. The documentation is a bit unclear, but if you don't have that file, create it (and blank worked).

3. Your actual error of class not found sounds like something fundamental is wrong.

4. I didn't need to publish to get it working.

**Comment by mschink** [comment]
Thanks for the detailed response.

I did try the `::class` notation for later versions of PHP, but no luck with that. I currently have a file footer.blade.php in `/templates/` so I'm not sure if this requirement is directory-sensitive.

I will try doing this with a brand new project, and report the results. These things might be nice to include in the documentation so there's less clutter of questions regarding setting up the package!

Cheers.

**Comment by jamesmorrish** [comment]
I've just been tearing my hair out for the past hour. It just wasn't running the boot method on the service provider. 

Eventually I got it to work by running

php artisan config:clear
php artisan config:cache
php artisan clear-compiled

**Comment by Mutasim0520** [comment]
I am also having the same problem? @mschink  did you solve it?

**Comment by mschink** [comment]
@Mutasim0520 I think if you follow what @jamesmorrish said above you'll find it works. It could be related to caching issues or perhaps my unfamiliarity with using Composer.
Because I have my entire project versioned on Git, the last resort was simple enough: clone a new copy of the project and see if it works there.

**Comment by TinoN** [comment]
@eugenevdm to make your post a little clearer:
I only got it working if the code is within the footer.blade.php file u mentioned.

1. composer require laracasts/utilities
2. in config/app.php add
```
'providers' => [
    ...,
    Laracasts\Utilities\JavaScript\JavaScriptServiceProvider::class,
    ...
];
```
3. in routes/web.php
```
Route::get('/', function () {
	JavaScript::put(['foo' => 'bar']);
    return view('welcome');
});
```
4. for example in welcome.blade.php add before </body>
```
         @include ('footer')
    </body>
```
5. create footer.blade.php and within this file add
```
<script>console.log(foo);</script>
```
6. php artisan serve
7. check console output, should be:
```
bar
```

ps: for me it work only this way, couldn't get it to work in another way
neither with 
```
php artisan config:clear
php artisan config:cache
php artisan clear-compiled
```
nor with a fresh
```
laravel new TestBlog
```
I need to access the PHP variables in my *.vue Component files; couldn't get it to work
