### ISSUE TITLE
not working in Laravel 5.4

### ISSUE THREAD

**Issue by elasticsteve** [laracasts/PHP-Vars-To-Js-Transformer#94]
I followed the instructions to the dot.

First, they should be updated to tell you to add
`Laracasts\Utilities\JavaScript\JavaScriptServiceProvider::class,`
to `app.php`

When I try to type `JavaScript` PHPstorm doesn't find the class. The only thing I get is `JavaScriptFacade`. Why? When I type JavaScript it uses the MongoDB Javascript, because it's the only thing that exists.

![pic1](https://cloud.githubusercontent.com/assets/10718044/22592180/5d453694-ea10-11e6-8aa2-ffc39ea05786.jpg)

When I use this:
```
   $data = [
          'name' => 'Steve',
          'email' => 'blabla@btinternet.com'
        ];

        JavaScriptFacade::put($data);

        return view('help');
```

I get `undefined` in the console when looking for `data` or `window.data`.

**Comment by blueoctopuswebdesigns** [comment]
It seems to be working fine for my laravel 5.4 install.
Did you try to console.log(data) in your footer.blade file?

**Comment by elasticsteve** [comment]
Yes, I tried. I doesn't matter, because it was fairly easy to pass the data myself into the blade view, so I removed `PHP-Vars-To-Js-Transformer` again and didn't bother to fix the problem.
